
CREATE SCHEMA DEMO;

USE SCHEMA DEMO;

CREATE TABLE STUDENT(
STUDENTID INTEGER,
STUDENTNAME VARCHAR(255),
BRANCH VARCHAR(255));


CREATE TABLE BRANCH(
    BRANCHID INTEGER,
    BRANCHNAME VARCHAR(255),
    BRANCHHEAD  VARCHAR(255)
)